// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIuZFuzXNCDT_1QECbTTgVlKHUGqI8Z7E',
    appId: '1:64169812202:web:0449b14781ad42d44ff793',
    messagingSenderId: '64169812202',
    projectId: 'bmdps-effa7',
    authDomain: 'bmdps-effa7.firebaseapp.com',
    storageBucket: 'bmdps-effa7.firebasestorage.app',
    measurementId: 'G-424W3WYQS4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCg1FiFS0-Y_iW05yPEqIyiNJgicx76UoI',
    appId: '1:64169812202:android:f0951921cb1577bb4ff793',
    messagingSenderId: '64169812202',
    projectId: 'bmdps-effa7',
    storageBucket: 'bmdps-effa7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIWTetPhmQ8c7q5pLWPjdHXT9altdIFdc',
    appId: '1:64169812202:ios:91b03308b8814c8a4ff793',
    messagingSenderId: '64169812202',
    projectId: 'bmdps-effa7',
    storageBucket: 'bmdps-effa7.firebasestorage.app',
    iosBundleId: 'com.example.documentManagementSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIWTetPhmQ8c7q5pLWPjdHXT9altdIFdc',
    appId: '1:64169812202:ios:91b03308b8814c8a4ff793',
    messagingSenderId: '64169812202',
    projectId: 'bmdps-effa7',
    storageBucket: 'bmdps-effa7.firebasestorage.app',
    iosBundleId: 'com.example.documentManagementSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIuZFuzXNCDT_1QECbTTgVlKHUGqI8Z7E',
    appId: '1:64169812202:web:4c50382bd03cac014ff793',
    messagingSenderId: '64169812202',
    projectId: 'bmdps-effa7',
    authDomain: 'bmdps-effa7.firebaseapp.com',
    storageBucket: 'bmdps-effa7.firebasestorage.app',
    measurementId: 'G-LBFLH6KT9C',
  );
}
